default_platform(:android)

platform :android do
  desc "Upload a new build to Play Store Internal Testing track"
  lane :internal do
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_apk: true,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft",
    )
    puts "✅ Uploaded to Play Store Internal Testing track!"
  end

  desc "Promote internal build to alpha"
  lane :alpha do
    upload_to_play_store(
      track: "internal",
      track_promote_to: "alpha",
    )
  end

  desc "Promote alpha build to production"
  lane :production do
    upload_to_play_store(
      track: "alpha",
      track_promote_to: "production",
    )
  end
end
